const Politics = [
  {
    name: "Lucas",
    number: "16",
    role: "Presidente",
    Partido: "PSF",
    votes: 123,
  },
  {
    name: "Pedro",
    number: "16",
    role: "Governador",
    Partido: "PSF",
    votes: 123,
  },
  {
    name: "Davi",
    number: "16",
    role: "Senador",
    Partido: "PSF",
    votes: 123,
  },
  {
    name: "Fabricio",
    number: "16",
    role: "Vereador",
    Partido: "PSF",
    votes: 123,
  },
  {
    name: "Alice",
    number: "23",
    role: "Presidente",
    Partido: "LL",
    votes: 123,
  },
  {
    name: "Julia",
    number: "23",
    role: "Governador",
    Partido: "LL",
    votes: 123,
  },
  {
    name: "Ana",
    number: "23",
    role: "Senador",
    Partido: "LL",
    votes: 123,
  },
  {
    name: "Otavio",
    number: "23",
    role: "Vereador",
    Partido: "LL",
    votes: 123,
  },
];
